#pragma once
#include <string>
#include <vector>

const std::vector<std::string> secrets = {
    "Can you believe those guys over at R&D solved the paradigm enigma?",
    "I heard we’re about to have a breakthrough with laser magnetisation.",
    "Superliminal guidance systems are going to be installed on the entire next batch.",
    "If we sold the secondary supplier inferior bolt plates, that might work its way over to the competition.",
    "Middle management in sector 7G don’t know what’s up.",
    "No one likes Doug’s team. What a bunch of jerks.",
    "I heard they were running new TR77 boards on their main database.",
    "We should water down their next fuel shipment.",
    "I’ve seen elementary school students who are better engineers.",
    "They convinced Spain to fund a new reciprocation program.",
    "Gary is gonna be on vacation next March.",
    "We better not let anyone know we misaligned the Scoville antenna array.",
    "I’m gonna get some coffee.",
    "Bob had no insurance for the appendix transplant, he’s gotta be hurting for cash.",
    "Lisa needs braces, but her family has no dental plan.",
    "Mona’s pet hamster is sick. Do you think that’s an exploitable security risk?",
    "We’re gonna pull ahead when we update the firmware on our corporate metastructure.",
    "Larry lost his ID card somewhere on vacation in Gibraltar.",
    "We literally cannot invalidate our nexus serial codes without data leaks.",
    "I’ve stopped checking the 13-7 servers since Elise went on vacation. No one looks there.",
    "They just decided to layoff half the security in the Istanbul branch.",
    "The Russia thing was just a red herring.",
    "Ottawa? What’s going on in OTTAWA?",
    "Well that was before the EU broke up when you could still get a decent sec-pack tracking system installed.",
    "A tunnel! Under a VOLCANO! I’m telling you the secret antarctic base is the coolest.",
    "The thing is those codes are stored in a submarine that cruises around off the gulf of Mexico.",
    "Emmanuel Santinogo is on our side! He’s a spy!",
    "That’s why we infiltrated their Boston branch.",
    "Don’t talk like that Phil! Though… if approached with the right offer, I’d think about selling out too.",
    "Did you hear about the upgraded NNX thruster coils?",
    "They’re moving the space infiltration team to the Washington campus.",
    "The other side thinks I’m a double agent, I’m getting access to so much!",
    "The backdoor we found to their megaserver gives us access to EVERYTHING.",
    "We’re going to monitor a meeting in Geneva tomorrow, place is already wired.",
    "Jane has been on sick leave for a long time, the boss is starting to wonder if she’s selling secrets.",
    "...but what if this call was intercepted? Can you imagine if they were listening right now?",
    "Did you hear that? Is this line secure?",
    "I hear a weird static, is that coming from your phone?",
    "This meeting room is wired up like crazy and connected to everything, maybe don’t talk about that in here.",
    "Could someone listen in through these server machines? I don’t THINK they have microphones?",
    "You heard that can hack into my music player? With what?! You’d need a pretty slick satellite network for that.",
    "If you had enough satellites in just the right position, you could theoretically listen in on anything happening in this room right here.",
    "We have a critical security error in the east wing. It’ll take three days to fix.",
    "His password is password1234. Seriously. I saw him typing it. He’s an executive administrator for this base!",
    "12 new spy satellites in geosynchronous orbit with London in the next four months.",
    "What a mess it would be if anyone heard that!",
    "And that’s top secret, buddy.",
    "I don’t want to hear mention of this again.",
    "You could blackmail someone with a fact like that.",
    "If the boss new…",
    "The competition can not find that out.",
    "Our plans would be ruined if this leaked.",
    "One phone call to a local newspaper and that would be shut down.",
    "It’s a human rights violation!",
    "You can’t invade privacy like that!",
    "Send that to my personal email.",
    "That’s not allowed offsite.",
    "The shipment will be there by midnight.",
    "We bribed customs there.",
    "Local officials are taken care of on this one.",
    "I know you are, but what am I?",
    "The whole thing is on this USB key, they’ll drop it off to the subcontractor on Queen street at 7:30.",
    "No no no no no no no. Oh… wait… maybe.",
    "I can accept those terms. A pleasure doing business with you.",
    "Gladys was writing an AI that sounded and behaved just like you. It would run their new lab.",
    "The military wanted to use that architecture for their Cloudnet AI.",
};
